// mypages.js
// 2023-03-01: by jcr

exports.genIndicePage = function(){
    var pagIndice = `
        <!DOCTYPE html>
        <html>
            <head>
                <meta charset="UTF-8"/>
                <title> Indice... </title>
                <link rel="stylesheet" href="w3.css"/>
            </head>
            <body>
                <div class="w3-card-4">
                    <div class="w3-container w3-deep-purple">
                        <li>
                            <a href="http://localhost:7777/pessoas">Lista de Pessoas</a>
                        </li>
                        <li>
                            <a href="http://localhost:7777/ordDesc">Lista de Pessoas Ordenadas</a>
                        </li>
                        <li>
                            <a href="http://localhost:7777/sexo">Distribuição por Sexo</a>
                        </li>
                        <li>
                            <a href="http://localhost:7777/desporto">Distribuição por Desporto</a>
                        </li>
                        <li>
                            <a href="http://localhost:7777/topsport">Top 10 Profissões</a>
                        </li>
                    </div>
                </div>
            </body>
        </html>
    `
    return pagIndice
}


exports.genMainPage = function(lista, data){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>Lista de Pessoas na Base de Dados (${lista.length})</h1>
            </header>
    
        <div class="w3-container">
            <table class="w3-table-all">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Idade</th>
                    <th>Sexo</th>
                    <th>Cidade</th>
                </tr>`

    for(let i=0; i < lista.length; i++){
        pagHTML += `
                <tr>
                    
                        <td>${lista[i].id}</td>
                        <td>
                            <a href="http://localhost:7777/pessoas/${lista[i].id}">
                                ${lista[i].nome}
                            </a>
                        </td>
                        <td>${lista[i].idade}</td>
                        <td>${lista[i].sexo}</td>
                        <td>${lista[i].morada.cidade}</td>
                </tr>
        `
    }

    pagHTML += `
            </table>
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by pessoas-server: ${data}</h5>
        </footer> 
    </div>
    </body>
</html>
    `
    return pagHTML
}

exports.genPessoaPage = function(pessoa, data){
    var pagHTML = `
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"/>
        <title>About people...</title>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-deep-purple">
                <h1>${pessoa.nome}</h1>
            </header>
    
        <div class="w3-container">
            `
    pagHTML += `
            
        </div>
    
        <footer class="w3-container w3-deep-purple">
            <h5>Generated by pessoas-server: ${data}</h5>
        </footer> 
    </div>
    </body>
</html>
    `
    return pagHTML
}


exports.genSexoPage = function(pessoas){
    var m = 0
    var f = 0
    var o = 0

    for (let i = 0; i < pessoas.length ; i++){
        if (pessoas[i].sexo == "masculino"){m++}
        if (pessoas[i].sexo == "feminino"){f++}
        if (pessoas[i].sexo == "outro"){o++}
    }

    sexoHTML = `
<!DOCTYPE html>
    <html>
        <head>
            Distribuição por Sexo
        </head>

        <table>
        <tr>
          <th>Sexo</th>
          <th>Número de Indivíduos</th>
        </tr>
        <tr>
            <td>
                <a href="http://localhost:7777/sexo/masculino">Masculino</a>
            </td>
          <td>${m}</td>
        </tr>
        <tr>
            <td>
                <a href="http://localhost:7777/sexo/feminino">Feminino</a>
            </td>
          <td>${f}</td>
        </tr>
        <tr>
            <td>
                <a href="http://localhost:7777/sexo/outro">Outro</a>
            </td>
          <td>${o}</td>
        </tr>
      </table> 
    </html>
    `

    return sexoHTML
}

exports.genSportsPage = function(pessoas){
    
    let dictSports = {}

    for (let i = 0; i < pessoas.length ; i++){
        for (let j = 0; j < pessoas[i].desportos.length ; j++){
            if (pessoas[i].desportos[j] in dictSports){
                dictSports[pessoas[i].desportos[j]] += 1
            }
            else dictSports[pessoas[i].desportos[j]] = 1
        }
    }

    sportsHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            Distribuição por Desporto
        </head>

        <table>
        <tr>
          <th>Desporto</th>
          <th>Número de Indivíduos</th>
        </tr> `

        for(let key in dictSports){
            sportsHTML += `
                <tr>
                    <td>
                        <a href="http://localhost:7777/desporto/${key}">${key}</a>
                    </td>
                    <td>
                        ${dictSports[key]}
                    </td>
                </tr>
            `
        }

        `
      </table> 
    </html>
    `

    return sportsHTML
}
exports.genTopPage = function(pessoas){

    let dictSports = {}

    for (let i = 0; i < pessoas.length ; i++){
        for (let j = 0; j < pessoas[i].desportos.length ; j++){
            if (pessoas[i].desportos[j] in dictSports){
                dictSports[pessoas[i].desportos[j]] += 1
            }
            else dictSports[pessoas[i].desportos[j]] = 1
        }
    }

    var array = Object.keys(dictSports).map(
        (key) => { return [key, dictSports[key]] });
    
    array = array.sort(
        (first, second) => { return first[1] - second[1] }
    );

    var keys = array.map(
        (e) => { return e[0] });


    topHTML =`
    <!DOCTYPE html>
    <html>
        <head>
            Distribuição por Desporto
        </head>

        <table>
        <tr>
          <th>Desporto</th>
          <th>Número de Indivíduos</th>
        </tr> `

        var i = 0
        for(let key in keys){
            if (i == 10) break
            topHTML += `
                <tr>
                    <td>
                        ${key}
                    </td>
                    <td>
                    <a href="http://localhost:7777/topsport/${dictSports[key]}">${dictSports[key]}</a>
                    </td>
                </tr>
            `
            i += 1
        }

        `
      </table>
    </html>
    `

    return topHTML
}